[#global-hub-importing-in-hosted-mode]
= Importing a managed hub cluster in the hosted mode (Technology Preview)

To enable `local-cluster` on your managed hub cluster, you must import it in the hosted mode.  

[#global-hub-importing-prereq]
== Prerequisites

- Enable `local-cluster` in the {global-hub} cluster.
- Install the latest {acm-short} version. 

[#global-hub-importing-hosted-mode]
== Importing a hub cluster in the hosted mode 

*Notes:*
To import an existing managed hub cluster in hosted mode, you only get support for imported managed hub clusters that use a `kubeconfig` file. {acm} uses this `kubeconfig` file to generate the `auto-import-secret`, which connects to your managed hub cluster. 

- Make sure this `kubeconfig` file is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command:
+
----
oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n <Managedhub Namespace>
----

- In hosted mode, {global-hub} does not support backup and restore.

Complete the following steps: 

. Import your managed hub cluster By setting label `global-hub.open-cluster-management.io/deploy-mode=hosted` to managedcluster
    With this label, {global-hub} does the following actions:
    - Imports the new managed hub cluster in hosted mode.
    - Install Globalhub Agent in the new managed hub cluster using hosted mode.
    - Disables the following `addons` in the new managed hub clusters namespaces: `applicationManager`, `certPolicyController`, and `policyController`. 
    - Changes the following managed hub clusters `addons` that are related to the new namespace: `work-manager`,`cluster-proxy`, and `managed-serviceaccount`. 
    - Changes these namespaces to `open-cluster-management-global-hub-agent-addon`. 
