[#global-hub-importing-managed-hub-in-default-mode]
= Importing a managed hub cluster in the default mode

[#global-hub-importing-prereq]
== Prerequisites

- Disable the cluster self-management in the existing {acm} hub cluster by setting the `disableHubSelfManagement` setting to `true` in the `multiclusterhub` custom resource. 

To import an existing hub cluster as a managed hub cluster, complete the following steps: 

. Import the managed hub cluster by completing the steps in link:../clusters/cluster_lifecycle/import_intro.adoc#import-intro[Cluster import introduction]. You must set the label `global-hub.open-cluster-management.io/deploy-mode=default` to the managedcluster when you import it.

. After the managed hub cluster is imported, check the {global-hub} agent status to ensure that the agent is running in the managed hub cluster by running the following command:
+
----
oc get managedclusteraddon multicluster-global-hub-controller -n <managed_hub_cluster_name>
----

Note: If you try to upgrade the Globalhub from 1.4.x, you must manually add the label `global-hub.open-cluster-management.io/deploy-mode=default` to all managed hub clusters.
